;
; general model settings
; default settting is equal to general model
;

;Global settings
[System]
INT15Retry=5	;Max retry when INT15 fail, def:5


;INT15 function to read ECRAM
[EcramRead]
AX=0x9611	;Def:0x9611
BX=0x0031	;Def:0x0031


;INT15 function to write ECRAM
[EcramWrite]
AX=0x9611	;Def:0x9611
BX=0x0131	;Def:0x0131


;INT15 function to get thermal
[GetThermal]
Count=3		;Thermal sensor count, Def:3(DTS, CPU, SYS)
AX=0x9611	;Def:0x9611
BX=0x002B	;Def:0x002B
CL=0x20		;Def:0x20


;INT15 function to get or set fan speed
[FanControl]
Count=2		;Fan count, Def:1
AX=0x9611	;Def:0x9611
BX_Get=0x002B	;BX value when get fan speed, Def:0x002B
CL_Get=0x21	;CL value when get fan speed, Def:0x21
BX_Set=0x022B	;BX value when set fan speed, Def:0x022B


;ECRAM control fan function, FanEcCtrl_n n means fan id
[FanEcCtrl_1]
Host=0x93	;Speed host control offset in ECRAM, Def:0x93
SetBit=0x10	;Speed host control set bit, Def:0x10(bit 4)
Control=0x94	;Speed control offset in ECRAM, Def:0x94
On=0x00		;Fan spped max, Def:0x00
Off=0xFF	;Fan speed 0, Def:0xFF

[FanEcCtrl_2]
Host=0x96	;Speed host control offset, Def:0x93
SetBit=0x10	;Speed host control set bit, Def:0x10(bit 4)
Control=0x97	;Speed control offset, Def:0x94
On=0x0F		;Fan spped max, Def:0x00
Off=0x00	;Fan speed 0, Def:0xFF


;ECRAM function to get battery voltage
[BattVoltage]
EcWriteOffset=0x02	;Get value function offset, def:0x02
EcWriteData=0x00	;Get value commend, def:0x00
EcReadOffset=0xE8	;Get battery voltage offset, def:0xE8


;ECRAM function to get battery capacity
[BattCapacity]
EcWriteOffset=0x02	;def:0x02
EcWriteData=0x00	;def:0x00
EcReadOffset=0xE4	;Get battery voltage offset, def:0xE8


;ECRAM function to get battery current
[BattCurrent]
EcWriteOffset=0x02	;def:0x02
EcWriteData=0x00	;def:0x00
EcReadOffset=0xEC	;Get battery voltage offset, def:0xE8


;ECRAM function to get battery thermal
[BattThermal]
EcWriteOffset=0x02	;def:0x02
EcWriteData=0x00	;def:0x00
EcReadOffset=0xEE	;Get battery voltage offset, def:0xE8


;ECRAM offset to get battery status
[BattStatus]
Batt1Offset=0x88	;Battery 1, def:0x88
Batt2Offset=0x89	;Battery 2, def:0x89
EcWriteOffset=0x02	;To get alarm, def:0x02
EcWriteData=0x01	;To get alarm, def:0x00
AlarmOffset=0xEC	;Battery alarm, def:0xEC


;ECRAM function to control adapter
[Adapter]
DataOffset=0x08		;ECRAM offset to write adapter command data, def:0x08
CmdOffset=0x00		;ECRAM offset to write adapter command, def:0x00
Cmd=0xE9		;ECRAM command of adapter, def:0xE9
DataOn=0x81		;Command data to set adapter on, def:0x81
DataOff=0x80		;Command data to set adapter off, def:0x80
ChkOffset=0x72		;ECRAM offset of adapter status, def:0x72
ChkBit=0		;Bit index of status, def:0
OnBitStatus=0		;Bit value when set on, def:0


;ECRAM function to control charge or discharge
[Charge]
DataOffset=0x08		;ECRAM offset to write charge command data, def:0x08
CmdOffset=0x00		;ECRAM offset to write charge command, def:0x00
Cmd=0xE7		;ECRAM command of charge, def:0xE7
DataOn=0x81		;Command data to set charge on, def:0x81
DataOff=0x80		;Command data to set charge off, def:0x80
ChkOffset=0x74		;ECRAM offset of charge status, def:0x74
ChkBit=4		;Bit index of status, def:4
OnBitStatus=0		;Bit value when set on, def:0
